all: CurrentDate.obj

CurrentDate.obj: CurrentDate.cpp
	cl CurrentDate.cpp
	copy CurrentDate.exe C:\Users\Андрей\controlwork\SPbCT_GanushkinAP\ControlWork\bin
	del C:\Users\Андрей\controlwork\SPbCT_GanushkinAP\ControlWork\bin\CurrentDate.exe
clean:
	del CurrentDate.exe
	del CurrentDate.obj
